title: Maya Zucker # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/maya-zucker/">LinkedIn</a> 
  <br>
  <a href="https://bowen.finance/cv/" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://www.GitHub.com/mayazucker/">GitHub</a>
theme: jekyll-theme-minimal
